### ISSUE TITLE
The latest master branch can not working 

### ISSUE THREAD

**Issue by netroby** [vzex/dog-tunnel#17]
The latest master branch can not working 

Process hang on After show message 
```
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
connect to server succeed
```

**Comment by vzex** [comment]
-remote dog-tunnel.tk:8018 ,please try this, the new version is 0.6, not compatible with the default server dog-tunnel.tk:8008

**Comment by netroby** [comment]
the default server port is hard code  in the source code? may we temp using 8018 instead with 8008?

**Comment by vzex** [comment]
yes, the arg "remote" 's  default value is "dog-tunnel.tk:8008", when this change became stable, I will update the  default server

**Comment by netroby** [comment]
1. the master branch should be working correct , if there must be new server port, we should change it, (I just create new pull request), 
2. i create another stable branch , with the default 8008 port, and it also worked.
3. i just  tested as you told me, it works, thanks for continue improve this software code.

**Comment by netroby** [comment]
https://github.com/netroby/dog-tunnel/tree/stable
The old , but stable branch.

**Comment by netroby** [comment]
The good side:
the latest master branch, decreased cpu usage. 

The bad side:
Connection may lost after initialized connection , force killed and try to connect again, it's working normal.

**Comment by vzex** [comment]
ok, I will follow this issue
