### ISSUE TITLE
Master branch, dtunnel will became freeze after a while 

### ISSUE THREAD

**Issue by netroby** [vzex/dog-tunnel#24]
Master branch, dtunnel will became freeze after a while 

or if a few minutes non active , the session will dead.

**Comment by vzex** [comment]
这个原因是这样：lite版本，两端会有心跳来检查是否连接正常，master版本，两个client之间没有心跳，客户端和服务端之间有心跳，所以udp通道失效的时候不会及时反应，之后会修正这个问题。

**Comment by netroby** [comment]
I tested the udp version also. the udp protocol not stable.
after a while, the udp packages can not reach other side .

So i tested the tcp protocol. it seems working well  and more stable than udp protocol

**Comment by vzex** [comment]
udp的数据相比tcp来说更容易被gfw，如果gfw怀疑你的流量有问题，会阻断udp的单向或者双向通讯，所以不是说udp不稳定，而是因为通讯数据已经不可达了

**Comment by netroby** [comment]
Yep. so the much more stable solutions , is socks5 over ssh, this is slowly, but more stable. (GFW not blocked SSH now)

**Comment by vzex** [comment]
ssh也会封的，目前dtunnel_lite的tcp模式还是比较稳定的，不过网络差的情况下表现不如udp好

**Comment by netroby** [comment]
UDP will be blocked by GFW  (If GFW sniffer your traffic not normal), so this is not a problem we can resolve. i will close this issue.
