### ISSUE TITLE
[UDPVersion] Connection freeze, kill and restart fixed it

### ISSUE THREAD

**Issue by netroby** [vzex/dog-tunnel#32]
[UDPVersion] Connection freeze, kill and restart fixed it.

After a while no activty, dog tunnel will freeze, and dead.
As this point, may dog tunnel choose exit process?

I am using systemd watching the dog tunnel process, if process exited. the sytemd will restart dog tunnel

**Comment by vzex** [comment]
你说的freeze是什么情况，无法连接？能否加-v看一下输出日志？连接内部有个ping超时机制，如果出现死链的时候理论上应该会自动重连才对，还有你说的这种情况大概多久会出现呢？我自己的程序大概连续运行了一个月,没出现类似问题。重启的时候只重启客户端吗

**Comment by netroby** [comment]
并不是无法连接。连接还在，但是再也无法使用（无法获取数据）。不知道您的默认超时时间是多长。大概30秒钟刷不出来数据，我觉得应该就先kill, 然后再重连。

**Comment by dearplain** [comment]
windows版本会出现这个问题，mac版不会，而且mac版速度快一倍。具体现象就是渐渐出现多个连接没数据过来的情况，后来所有新建立的连接都没有数据过来。有一个规律是如果同一个地址频繁请求，传输大量数据，就会慢慢出现这个问题。加了-timeout参数之后好了一些。

**Comment by dearplain** [comment]
ps. 用的是0.90 lite， windows是win7，mac是Yosemite.

**Comment by vzex** [comment]
@dearplain 是不是-pipe 默认1个连接，然后正在传输大量数据（下载或者看视频）的时候去浏览其他网页或者什么的，会很慢？

**Comment by dearplain** [comment]
@vzex   不是，pipe设过1、5、10 ，没改善。比如看youtube，拉进度条到没缓冲的地方，速度立即爆降，然后各种卡。狗洞在win下比ss速度差一点，但是在mac下是ss的两倍。之前说错了，mac下也会发生卡顿，只是概率比较小。
