### ISSUE TITLE
dtunnel_lite 只允许 socks5 模式？

### ISSUE THREAD

**Issue by GameXG** [vzex/dog-tunnel#35]
2015/08/29 13:17:29 try dial xxx.com:port ok 0 [::]:60996
2015/08/29 13:17:29 request auth key 148156
2015/08/29 13:17:29 request encrypt
2015/08/29 13:17:29 debug aeskey 115861556875
2015/08/29 13:17:29 server force do action socks5
client service start success,please connect :88
2015/08/29 13:17:37 Request Message VER or RSV error!
2015/08/29 13:18:12 Request Message VER or RSV error!

想通过 dtunnel_lite 做个安全隧道将服务器的内部服务映射到本地，方便本地使用，看起来是不支持？

**Comment by GameXG** [comment]
最近正有跨 NAT 连接各个服务器建立内部网络的需求，找到了这个项目。
可惜不熟悉golang，没法贡献代码...

**Comment by vzex** [comment]
你好，服务端请加参数-action "",服务端指定-action是可以强制限制连接的客户端的行为的，默认socks5

**Comment by GameXG** [comment]
非常感谢，已正常工作。
