### ISSUE TITLE
不支持 IPv6 ?

### ISSUE THREAD

**Issue by GameXG** [vzex/dog-tunnel#41]
socks5 代理模式试图访问 ipv6 域名，无法访问，不支持 ipv6？

**Comment by vzex** [comment]
你的sock5服务端支持ipv6吗，有没有尝试过在机器上直接telnet到无法访问的ipv6地址？

**Comment by GameXG** [comment]
抱歉，忘了说了，使用的是 dtunnel_lite 版本。

服务端直接 telnet ipv6地址：
vps> telnet ipv6.google.com 80                                                               ~
Trying 2607:f8b0:4005:803::200e...
Connected to ipv6.l.google.com.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 200 OK
Date: Fri, 11 Sep 2015 03:54:03 GMT
Expires: -1
Cache-Control: private, max-age=0

使用socks5远端解析，发送的 atyp = 0x03 ，地址是 ipv6.google.com 的请求。
dtunnel_lite 回应是
ver = 5,rep = 4,rsv = 0, atyp =1
· X’04’ 主机不可达

**Comment by vzex** [comment]
能否把服务端加-v的输出发我一下看看，dtunnel在socks5连接异常时返回的信息不太对，这个我先改一下，但是问题没出在这个

**Comment by GameXG** [comment]
> /home/gamexg/dtunnel/dtunnel_lite -service 0.0.0.0:1500 -auth 000 -action "" -dnscache 10 
-v

服务端日志如下：
2015/09/12 21:44:14 tcp ipv6.google.com:80 3 80
2015/09/12 21:44:14 tcp ipv6.google.com:80 3 80
2015/09/12 21:44:14 add host ipv6.google.com to dns cache
2015/09/12 21:44:14 connect to local server fail: dial tcp: missing ']' in address [2607:80
2015/09/12 21:44:14 connect to local server fail: dial tcp: missing ']' in address [2607:80
2015/09/12 21:44:15 tcp ipv6.google.com:80 3 80
2015/09/12 21:44:15 connect to local server fail: dial tcp: missing ']' in address [2607:80
2015/09/12 21:44:20 tcp ipv6.google.com:80 3 80
2015/09/12 21:44:20 connect to local server fail: dial tcp: missing ']' in address [2607:80
2015/09/12 21:44:25 tcp ipv6.google.com:80 3 80
2015/09/12 21:44:25 connect to local server fail: dial tcp: missing ']' in address [2607:80
2015/09/12 21:44:25 tcp ipv6.google.com:80 3 80
2015/09/12 21:44:25 connect to local server fail: dial tcp: missing ']' in address [2607:80

**Comment by vzex** [comment]
https://github.com/vzex/dog-tunnel/commit/a9fcdef49bc731b6451a4d6b530d1341659b8d55 你好，该问题已修正，请下载最新代码测试一下看看

**Comment by GameXG** [comment]
非常感谢。

请问 lite 和标准版是一个源代码吗？
直接 ./release.sh 出来的是标准版本。
请问 lite 怎么编译？

**Comment by vzex** [comment]
git checkout udpVersion
make client

**Comment by GameXG** [comment]
IPv6 测试成功。

但是碰到了一个奇怪的问题，编译出来的新版本无法访问 https 类型的网站（下载的二进制发布版没问题），例如：
https://github.com/vzex/dog-tunnel
https://ipv6.google.com (http://ipv6.google.com 正常)
https://twitter.com/
https://www.taobao.com/

chrome提示：SSL 连接出错

ERR_SSL_PROTOCOL_ERROR
隐藏详细信息
无法与服务器建立安全连接。可能是服务器出现了问题，也可能是您没有服务器要求的客户端身份验证证书。


环境信息：
服务器：ubuntu 14.04
客户端：win10
go version go1.2.1 linux/386
源代码版本：
commit a9fcdef49bc731b6451a4d6b530d1341659b8d55
Author: vzex <vzex@163.com>
Date:   Mon Sep 14 20:07:05 2015 +0800

    fix ipv6 parse bug in dnscache



客户端日志：
dtunnel_lite -service www.aaa.net:1500 -local :5555 -auth 000 -encrypt -action socks5 -v
2015/09/16 09:21:51 try dial www.aaa.net:000 ok 0 [::]:60565
2015/09/16 09:21:51 request auth key 000
2015/09/16 09:21:51 request encrypt
2015/09/16 09:21:51 debug aeskey 145131651144
client service start success,please connect :5555
2015/09/16 09:21:53 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:53 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:54 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:54 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:57 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:57 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:58 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:58 tcp ipv6.google.com:443 3 443
2015/09/16 09:22:00 tcp ipv6.google.com:443 3 443
2015/09/16 09:22:00 tcp ipv6.google.com:443 3 443
2015/09/16 09:22:01 tcp ipv6.google.com:443 3 443
2015/09/16 09:22:01 tcp ipv6.google.com:443 3 443
2015/09/16 09:22:02 tcp clients4.google.com:443 3 443
2015/09/16 09:22:02 tcp clients4.google.com:443 3 443
2015/09/16 09:22:03 tcp clients4.google.com:443 3 443
2015/09/16 09:22:03 tcp www.google.com:443 3 443
2015/09/16 09:22:04 tcp www.google.com:443 3 443
2015/09/16 09:22:04 tcp www.google.com:443 3 443
2015/09/16 09:22:04 tcp www.google.com:443 3 443
2015/09/16 09:22:04 tcp www.google.com:443 3 443
2015/09/16 09:22:04 tcp www.google.com:443 3 443
2015/09/16 09:22:05 tcp www.google.com:443 3 443
2015/09/16 09:22:05 tcp www.google.com:443 3 443
2015/09/16 09:22:05 tcp www.google.com:443 3 443
2015/09/16 09:22:05 tcp www.google.com:443 3 443
2015/09/16 09:22:05 tcp www.google.com:443 3 443
2015/09/16 09:22:05 tcp www.google.com:443 3 443
2015/09/16 09:22:05 tcp www.google.com:443 3 443
2015/09/16 09:22:06 tcp www.google.com:443 3 443
2015/09/16 09:22:06 tcp www.google.com:443 3 443
2015/09/16 09:22:06 tcp www.google.com:443 3 443
2015/09/16 09:22:06 tcp www.google.com:443 3 443
2015/09/16 09:22:07 tcp www.google.com:443 3 443

服务端日志：
> ./dtunnel_lite -service 0.0.0.0:1500-auth 000 -action "" -dnscache 10 -v                                  
service start success,please connect 0.0.0.0:1500
2015/09/16 09:21:33 add udp session ?.?.?.?:60565
2015/09/16 09:21:33 add pipe 0 for ?.?.?.?:60565
2015/09/16 09:21:33 got encrpyt key 145131651144
2015/09/16 09:21:33 init action socks5
2015/09/16 09:21:33 currid 1 ?.?.?.?:60565
2015/09/16 09:21:35 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:35 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:35 add host ipv6.google.com to dns cache
2015/09/16 09:21:36 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:36 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:39 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:39 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:40 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:40 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:42 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:42 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:42 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:43 tcp ipv6.google.com:443 3 443
2015/09/16 09:21:44 tcp clients4.google.com:443 3 443
2015/09/16 09:21:44 add host clients4.google.com to dns cache
2015/09/16 09:21:44 tcp clients4.google.com:443 3 443
2015/09/16 09:21:45 tcp clients4.google.com:443 3 443
2015/09/16 09:21:45 tcp www.google.com:443 3 443
2015/09/16 09:21:45 add host www.google.com to dns cache
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:46 tcp www.google.com:443 3 443
2015/09/16 09:21:47 tcp www.google.com:443 3 443
2015/09/16 09:21:47 tcp www.google.com:443 3 443
2015/09/16 09:21:47 tcp www.google.com:443 3 443
2015/09/16 09:21:47 tcp www.google.com:443 3 443
2015/09/16 09:21:47 tcp www.google.com:443 3 443
2015/09/16 09:21:47 tcp www.google.com:443 3 443
2015/09/16 09:21:48 tcp www.google.com:443 3 443
2015/09/16 09:21:48 tcp www.google.com:443 3 443
2015/09/16 09:21:48 tcp www.google.com:443 3 443

**Comment by GameXG** [comment]
确认是 60fea613da727222c204c5eeef4884a75576fa15 造成的 http ssl 无法正常使用。

应该是忘记处理 atyp 为3、4时 addr 长度不同的问题了。理论上http请求也会出错，可能是chrome自动纠正了错误。

但是没学过 go ，没办法改代码。。。

**Comment by vzex** [comment]
是socks5 server端返回response信息的atyp不对，应该是1，详见http://www.360doc.com/content/13/0927/08/11681374_317366312.shtml
