### ISSUE TITLE
麻烦问下我不想用公共帐号 能否自己搭建帐号服务器？

### ISSUE THREAD

**Issue by lingdu0001** [vzex/dog-tunnel#49]
这个部分是开源的还是？

**Comment by vzex** [comment]
你好，官网下载的打包文件中有dtunnel_s为服务端，或者源代码自行编译make server
测试如下
./dtunnel_s 启动服务端，默认8000端口，默认ssl是false,dtunnel的ssl默认开，-ssl false关闭
./dtunnel -reg a -remote 127.0.0.1:8000 -local socks5  -ssl false //注册socks5服务
./dtunnel -link a -remote 127.0.0.1:8000 -local :8787 -ssl false //开启8787端口为socks5服务

**Comment by ferocknew** [comment]
开启服务端以后 ，一直提示：

2016/11/30 23:09:51 invalid query2!
too large data!

**Comment by vzex** [comment]
你好，-ssl false换成-ssl=false试一下
