### ISSUE TITLE
加速游戏会导致游戏tcp连接无法正常建立

### ISSUE THREAD

**Issue by hulucc** [vzex/dog-tunnel#50]
客户端proxifier+dtun-lite，win7 64bit
dtunnel_lite.exe -servicexxxx:20000 -action socks5 -local :1090
服务端，ubuntu 14.0
./dtunnel_lite -service 0.0.0.0:20000 -action ""

游戏登录后有2个tcp长连接，一个负责聊天系统，一个负责游戏场景
首次登录没有问题，但是当发生换线或者换角色时，游戏场景tcp连接会断开重新连接另一台服务器
用了dtun之后该连接断开后就没有再连接了，游戏也就卡住了。

目前尝试过的操作：
添加或删除xor,encrypt,auth,pipe
sock5代理，端口映射（通过shadowsocks，直连ss并无问题）

**Comment by vzex** [comment]
你好，可以再具体描述下dtunnel_lite的使用方式吗，我看你的连接都是长连接，但是开的服务是socks5，这个主要针对http短连接的，所以连接你的1090端口主要是做哪部分请求的代理呢？

**Comment by hulucc** [comment]
你好，主要是做TCP长连接的代理

我尝试过sock5和端口映射
sock5的使用方式就如上面写的那样
端口映射的话是这样使用的：
服务端不变
客户端：
dtunnel_lite.exe -service xxxx:20000 -action xxxx:443 -local :2000
其中 443是我服务器上的ss服务端，再使用ss客户端连接locaohost:2000，最后通过proxifier把游戏连接到ss上

sock5不适合的话，游戏类的加速用什么方式配置会比较好呢？

**Comment by vzex** [comment]
抱歉，没有注意到proxifier这个软件，大致了解你的工作模式了，能否告知一下是哪个游戏，我可以测试一下，ss不走加速直接和proxifier连接是正常的吗？

**Comment by vzex** [comment]
你好，请使用最新代码编译或者官网下载最新的release 1.11版本，修复了非smart的socks5模式的bug

**Comment by hulucc** [comment]
无论是sock5模式还是端口映射，问题都已经解决了，谢谢！
顺带一提是什么BUG导致的呢？

**Comment by vzex** [comment]
你好，是因为新加的smart智能模式引起的老的模式tcp连接没有正常断开的问题。你也可以尝试加一下-smartN 5(5是推荐值，可自行调整)这个参数切到智能模式，这个模式下面程序会自动检测请求的连接是否需要走远端代理。不过游戏的话一般都是长连接，可能没有效果，甚至可能会导致异地登陆等问题
