### ISSUE TITLE
源码怎么编译出lite端？

### ISSUE THREAD

**Issue by bhzhu203** [vzex/dog-tunnel#54]
github 上的源码编出来的是 server端和client端的，没看到有生成 lite

all: 
	@make release
release:
	make client
	make server
debug:
	make client_debug
	make server_debug
client_debug:
	@go build -gcflags "-N -l" -o dtunnel_d client.go
server_debug:
	@go build -gcflags "-N -l" -o dtunnel_s_d server.go
client:
	@go build -ldflags "-s -w" -o dtunnel client.go
server:
	@go build -ldflags "-s -w" -o dtunnel_s server.go
clean:
	@rm -rf dtunnel dtunnel_d dtunnel_s_d dtunnel_s
.PHONY: all debug release client_debug server_debug client server clean

makefile里面没有看到lite，谢谢

**Comment by vzex** [comment]
git checkout udpVersion然后make
