### ISSUE TITLE
dtunnel 非lite版不通

### ISSUE THREAD

**Issue by chmis8000** [vzex/dog-tunnel#56]
远端、近段都是win系统，
远端：dtunnel -reg zzcs -local :88  -ssl false
      远端这个88访问是没问题的，web server，近端可以直接 http://192.168.1.10:88/ 访问。
近端： dtunnel -link zzcs -local :8888  -ssl false

近端的错误是：cannot connect to bind addr:88
连接方式显示p2p, 另外加参数 -mode 2 ，仍旧显示p2p模式

**Comment by vzex** [comment]
你好，reg端，-local 请指定 192.168.1.10:88，另外所有的参数最好用-xxx=xx的形式，-ssl false这种格式可能会导致后面的参数无效

**Comment by chmis8000** [comment]
以下，仍旧无法使用，请确认你们windows模式测试过，正常？:
远端： dtunnel -reg=zzcs -local=192.168.1.10:88 -ssl=false

近端1： dtunnel -link=zzcs -local=10.0.2.15:8888 -ssl=false 
 近端则只提示： connect to server succeed ，之后就回到命令提示符状态
近端2： dtunnel -link zzcs -local 10.0.2.15:8888 -ssl false
 近端则只提示：connect to server succeed
2016-07-17 14:47:47 serverName invalid!!!
read tcp 10.0.2.15:1817->65.181.125.112:8000: use of closed network connection
然后回到提示符状态

**Comment by vzex** [comment]
如果不指定remote，默认使用的是狗洞官网服务器，ssl必须指定为true

**Comment by chmis8000** [comment]
感谢，远端和近端 都加了 -remote， OK了
