### ISSUE TITLE
dtunnel 非lite版 自搭server，报错

### ISSUE THREAD

**Issue by chmis8000** [vzex/dog-tunnel#57]
server端，远端 都是win系统
server端直接exe运行，阿里云服务器，如IP是：219.235.1.203
远端：dtunnel -reg a -remote 219.235.1.203:8000 -local :88  -ssl false
  远端隔几秒就显示一行： connect remote err:EOF
近端：没试

**Comment by vzex** [comment]
近端 telnet 219.235.1.203 8000能连接成功吗

**Comment by chmis8000** [comment]
上次测试忘记了，本次测试：
启动  kcptunS.exe 无参数，提示：
version:20160602
listtening on 0.0.0.:29900
....
用 netstat -an  测试，没有任何程序监听 TCP或UDP的 8000端口，但有29900 udp监听。
但远端无法连接：
dtunnel -reg a -remote 219.235.1.203:29900 -local :88 -ssl false
循环提示：
connect remote err:dial tcp 219.235.1.203:29900: connectex: No connection could be made because the target machine actively refused it.

**Comment by vzex** [comment]
这个。。。kcptun作为服务端？哥走错片场了？

**Comment by fcying** [comment]
开始也碰到这个问题, 把参数都改成 用`=`连接后就成功了....`-ssl=false` 这样

**Comment by chmis8000** [comment]
是串了，服务端用错了。
但帖头问题，如 fcying 改= 成功了。 
可以关闭帖子了

**Comment by shellus** [comment]
@chmis8000  不应该关闭这个Issue，这是一个存在的Bug
