### ISSUE TITLE
我看代码只实现了STUN，有没有打洞失败的可能？

### ISSUE THREAD

**Issue by metalwood** [vzex/dog-tunnel#59]
两个不同局域网的内网节点之间通过STUN协议是不是能保证一定连通？如果不保证，是不是应该用TURN做补充，或者用ICE？谢谢！

**Comment by vzex** [comment]
狗洞服务端其实是一个stun turn和ice的简化版(山寨)实现，之前stun一直采用第三方服务器通过-stun来指定的，上个版本才刚刚加入一个内部山寨版，其实就是默认监听的那个8018端口实现的功能。目前这个方案，不能保证一定连通的，某些特定的nat设备下通过这种方案是一定不可连通的(某些论文提到过会通过猜测端口映射规则的方式确定端口https://tools.ietf.org/id/draft-takeda-symmetric-nat-traversal-00.txt，但也是实验性质的方案)，这个情况下只能通过狗洞的服务器做中转来通讯了。

**Comment by metalwood** [comment]
谢谢回复。TURN的实际数据也是走的中转服务器，标准STUN也有适用范围，只要dog-tunnel的简化版STUN能实现和标准STUN一样的目的，覆盖场景不减少，其实我想不必在意是否实现得标准，因为KCP本来就不是标准。提问的时候我以为ICE是比STUN更新的技术能给更多的情况下实现打洞，后来我知道其实也用到了中转，只是结合了STUN和TURN。

**Comment by metalwood** [comment]
另外，有几个疑问：
1、dog-tunnel在使用和不适用中转服务器的情况下，是不是把STUN和TURN在接口上揉合到一起了？
2、dog-tunne是否支持无需打洞时的直连（像kcptun那样），如果支持，直连接口和打洞接口是否相互独立？
3、dog-tunnel内部是否做了kcp、fec、mtu等等的参数自适应调整？还是固化了默认参数？

**Comment by vzex** [comment]
1 不好意思，狗洞没有实现turn，上面写错了
2 参考udpVersion这个分支，dtunnel_lite版本
3 dtunnel_lite 有-kcp参数用于kcp相关的设置，master分支还没支持
