### ISSUE TITLE
服务器端连接的密码要怎么设置的?

### ISSUE THREAD

**Issue by fcying** [vzex/dog-tunnel#60]
设 `./dtunnel_s -ssl=true -cert=server.crt key=server.key` 一直提示`load key file error open : no such file or directory`

我目录下有这2个文件的

**Comment by vzex** [comment]
dtunnel_s 可以设置ssl相关证书，之后客户端通过ssl证书连接，服务端同时可以指定mysql数据库，auth目录下的sql是建表语句，通过数据库来设置账号密码，数据库不要直接操作，有个-admin命令开启后台管理端口，之后可以通过http请求进行用户的加 ，减， 流量限制之类的操作，这块目前没有文档，建议可以看看admin/admin.go尝试使用
