### ISSUE TITLE
那么，请问如何搭建自己的狗洞服务器呢

### ISSUE THREAD

**Issue by kkstun** [vzex/dog-tunnel#65]
请问如何搭建自己的狗洞服务器呢，也是用udp端口吗。

**Comment by kkstun** [comment]
是需要一个公网ip和tcp端口吗

**Comment by chmis8000** [comment]
那是必须的，没公网ip就别想搭服务器了

**Comment by kkstun** [comment]
我看了下代码，是只要一个公网tcp端口还是一个tcp+一个udp端口呢

**Comment by kkstun** [comment]
自建服务器，客户端连接出现 connect remote err:EOF  服务器invalid query2!
too large data!

**Comment by chmis8000** [comment]
服务端出现的吧， 应该是有别人扫描服务器，胡乱尝试端口

**Comment by kkstun** [comment]
是本地自己调试出现的

**Comment by kkstun** [comment]
加了-ssl=false问题解决
