### ISSUE TITLE
lite 版中 -cache 开启后，缓存时间是永久的吗？ 

### ISSUE THREAD

**Issue by katosun2** [vzex/dog-tunnel#66]
lite 假如开启了 -cache 缓存，文件缓存时间是不是永久的？

如果是永久的，缓存是不是必须手动清理？

如果不是永久的，缓存时间是怎么定义的？

**Comment by vzex** [comment]
这个功能，其实是方便对静态网站做离线镜像用的，加了-cache，会单独有一个goroutine启动，对于每条狗洞代理的http请求，这个goroutine会单独再去请求一次，然后将返回的内容作为./cache下同路径同文件名保存下来，这个功能由于目前作用不是很大，所以没有缓存时间的概念，每次get请求都会去重新单独再去请求一次，写文件

**Comment by katosun2** [comment]
明白了，多谢。
