### ISSUE TITLE
建议增加一些功能，以便适应恶劣的网络环境

### ISSUE THREAD

**Issue by bhzhu203** [vzex/dog-tunnel#68]
dog-tunnel非常好用，本人用它做游戏加速使用的。

但是在高峰时期，平时很好的日本网络也会丢包（ping 服务器ip也会丢包），估计是骨干网络带宽跑满了。

最近在使用kcp-tun，可惜只能转发tcp流量。但是它两点特性是非常好的：

1。数据压缩
2. 前向纠错。  （好像这个特性可以允许基础数据包丢失20%仍然能 完整传输，换言说能允许20%的丢包？）
反正在公司的海外项目上使用KCP-TUN，在比较容易抖动的香港到大陆的传输过程，显得比较稳定。

dog-tunnel可以在客户端这里随意变换参数去连接，这点是比较赞的。

**Comment by vzex** [comment]
可以作为下个功能点支持

**Comment by bhzhu203** [comment]
kcptun 有reed-solomon 纠删码的支持，好像可以在UDP丢包的环境下很好地工作，即使丢包了也能很好地还原原始数据。
https://github.com/klauspost/reedsolomon  要不参考一下这个？这个是用go写的实现。

**Comment by vzex** [comment]
master分支已经支持上述实现，这两天会移植到lite版，数据压缩也会稍后支持
