### ISSUE TITLE
重大问题：断网重新连接后提示服务已存在

### ISSUE THREAD

**Issue by QQ2017** [vzex/dog-tunnel#71]
你好，断网重新连接后提示服务已存在。
例如我注册一个远端，名字为myName，注册成功并且监听，当远端所在的机器发生网络中断，比如adsl重新拨号、网卡禁用再启用等情况，虽然远端10秒后会自动尝试连接服务器，但是此时却提示服务名已存在，即使关掉进程重新打开也是一样，也就是说服务器不能将异常断开的服务删除，除非用管理接口删除，或重启服务器进程，这对于无人值守的内网用户来说非常不方便，请问可以解决这个BUG吗，或者有什么解决方法？下面是我在远端机器禁用网卡再启用网卡后的狗洞的输出信息：

> C:\Users\Administrator\Desktop\dtunnel>dtunnel.exe -reg m
yname1 -local localhost:7899 -clientkey 123456
connect to server succeed
2016-11-23 07:47:38 register service ok, user:
read tcp 192.168.1.186:49260->65.181.125.112:8000: wsarecv: An existing connecti
on was forcibly closed by the remote host.
connect remote err:dial tcp: lookup dog-tunnel.tk: getaddrinfow: No such host is
 known.
connect remote err:dial tcp: lookup dog-tunnel.tk: getaddrinfow: No such host is
 known.
connect remote err:dial tcp: lookup dog-tunnel.tk: getaddrinfow: No such host is
 known.
connect to server succeed
2016-11-23 07:48:34 already have the ServerName!
read tcp 192.168.1.186:49261->65.181.125.112:8000: use of closed network connect
ion
connect to server succeed
2016-11-23 07:48:46 already have the ServerName!
read tcp 192.168.1.186:49262->65.181.125.112:8000: use of closed network connect
ion
connect to server succeed
2016-11-23 07:48:57 already have the ServerName!
read tcp 192.168.1.186:49263->65.181.125.112:8000: use of closed network connect
ion
connect to server succeed
2016-11-23 07:49:08 already have the ServerName!
read tcp 192.168.1.186:49266->65.181.125.112:8000: use of closed network connect
ion

**Comment by vzex** [comment]
你好，这个问题是由于网络非正常断开引起的，服务端以为连接还在，解决方案一个是每次注册都把原来已有的注册方踢掉，另外一个就是加入超时检查，考虑把这两种作为服务端启动参数来选择，用户自己决定到底采用哪种方案

**Comment by QQ2017** [comment]
超时检测如何设置，是不是还没有这个功能

**Comment by vzex** [comment]
还没有做

**Comment by QQ2017** [comment]
希望能快点发布新版解决这个问题...
