### ISSUE TITLE
使用dtunnel_s 自己搭建的服务器，根本不行，连接的时候报错

### ISSUE THREAD

**Issue by chengziqing** [vzex/dog-tunnel#72]
2016/11/23 14:46:27 invalid query2!
too large data!

请官方跟个搭建教程，使用你们的服务器太慢

**Comment by QQ2017** [comment]
加个这个试试  -ssl=false

**Comment by QQ2017** [comment]
加个这个试试  -ssl=false

**Comment by QQ2017** [comment]
加个这个试试  -ssl=false

**Comment by ddyllen-z** [comment]
我自己搭建了好久没成功。文档太少，要么就是文档命令执行出来都报错，照搬执行都报参数没有定义。

**Comment by vzex** [comment]
参考readme，文档已完善，如有疑问再开issue吧

**Comment by seatrix** [comment]
server：
 ./dtunnel_s -addr "0.0.0.0:22001" -addrudp "0.0.0.0:22002" -admin "0.0.0.0:22003"

client：
dtunnel -link=sdqdmll3711 -local=:8788 -clientkey=31415926  -remote="12345.com:22001"  -buster="12345.com:22002" -ssl=false
