### ISSUE TITLE
fatal error: runtime: cannot allocate memory

### ISSUE THREAD

**Issue by satifanie** [vzex/dog-tunnel#73]
使用版本arm_lite, 1.20
我知道上述异常。但是情况很奇怪:
我实际内存还剩余180M, 增加了swap之后就可以了。

**Comment by vzex** [comment]
你好，能否具体描述一下
是服务端还是客户端？
top命令截图能否提供？或者描述一下其他程序的cpu 内存占用情况？
程序的运行时间？

**Comment by satifanie** [comment]
客户端的。运行在路由器里的。 梅林固件，我已经重置了，希望再试一下。家里一个 export GOGC=40 不知道是什么作用的？

**Comment by satifanie** [comment]
2016/12/03 09:41:04 handshakefail with code -1
2016/12/03 09:41:04 try dial err handshake fail,1
2016/12/03 09:41:04 sys will reconnect pipe 1 after 3 seconds
2016/12/03 09:41:04 session timeout
2016/12/03 09:41:04 handshakefail with code -1
2016/12/03 09:41:04 try dial err handshake fail,1
2016/12/03 09:41:04 sys will reconnect pipe 3 after 3 seconds
现在发现用一段时间后 会出现上面的问题，导致服务中断，我增加一个timeout 不知道会不会好点

**Comment by satifanie** [comment]
服务器资源不够，OPENVZ资源竞争的厉害

**Comment by vzex** [comment]
上面的的handshake fail有可能是临时封了，可以尝试用一下新加的-confusion参数，看看有没有缓解
