### ISSUE TITLE
-encrypt对时间敏感对吗？

### ISSUE THREAD

**Issue by satifanie** [vzex/dog-tunnel#74]
是这样的，前段时间，我有反馈说：在树莓派上运行一段时间之后会断开。
最近我定位了一下，发现定时ntp就不会了。
是这样的吗？服务器与客户端时间要相近，
有没有其他的更好的方式？有时候真难以保证时间一致！

**Comment by vzex** [comment]
你好，两端时间并没有这种检查，如果只是在派上的话，派的时间经常变，是有可能导致正在持续运行的实例的连接因为触发错误的超时检查而断开的

**Comment by satifanie** [comment]
已经加上了 ntpdate定时更新了。 断开，有可能是运营商
