### ISSUE TITLE
编译了一下dtunnel_lite 1.30的感受

### ISSUE THREAD

**Issue by satifanie** [vzex/dog-tunnel#75]
服务器端开启了 -dnscache，服务器客户端都是用自行编译版本的。另外客户端是 arm版本，服务器是 Linux x64
客户端参数：
1.  组合 -compress -confusion -encrypt -xor xxxx -session_timeout 60 -pipe 4。 基本上无响应
2. 组合 -confusion -encrypt -xor xxxx -session_timeout 60 -pipe 4  速度急剧下降，u2b原有10k 的速    度，现在是300，视频只能这样
3. 现在使用  -encrypt -xor xxxx -session_timeout 60 -pipe 4，速度10k

**Comment by chmis8000** [comment]
意思是 -compress  有问题，根本不能用？

**Comment by vzex** [comment]
-confusion如果使用没有问题的话请不要使用，这个只是在连接国外vps出现频繁的连接断开时的一种实验性的策略，并不能加速网络，反而会使网络变慢

**Comment by satifanie** [comment]
@chmis8000 测试时间不长，而且用的树莓派，性能本本身就低。
@vzex  目前还是使用了1.20版本了。使用还是会断上一段时间，今天决定切换使用443 端口，试试是不是因为 运营商的问题，导致用一段时间就中断。

**Comment by vzex** [comment]
-compress bug已修正,另推荐使用-ps -ds两个参数可起到加速效果
