### ISSUE TITLE
dtunnel_lite 带 -compress 就是有问题啊

### ISSUE THREAD

**Issue by chmis8000** [vzex/dog-tunnel#76]
参数 -pipe 5 -compress -v
小包，没问题。大包（应该不超过200KB），近端有如下错误：
 force quit for read error
 remove pipe 12
write err closed
然后就是卡顿超过2分钟 才数据传输过来.

同样，不加 -compress 不管多大的包都没问题。

**Comment by vzex** [comment]
你好，可能是压缩解压预分配的cache不够用了，我查证一下

**Comment by chmis8000** [comment]
老大终于来了，年关都忙啊

**Comment by vzex** [comment]
恩，事情是有点杂没闲心看issue，今天刚好瞥了一眼就修修，你更新下看看有问题吗

**Comment by vzex** [comment]
应该还没好，等我下个提交
