### ISSUE TITLE
关于端口段支持

### ISSUE THREAD

**Issue by MiuKaShi** [vzex/dog-tunnel#77]
s: ./dtunnel_lite -service 127.0.0.1:1234
c: ./dtunnel_lite -service 127.0.0.1:1234 -local :8787 -action 127.0.0.1:22
请问以上代码如何实现端口段的映射转发呢

**Comment by vzex** [comment]
这个的意思是把你本地的22映射到本地8787端口上，即你的8787端口就是ssh可以连接的端口
如果你把s端架在远程机器上
s: ./dtunnel_lite -service 远程ip:1234
c: ./dtunnel_lite -service 远程ip:1234 -local :8787 -action 127.0.0.1:22
那么s端的8787端口就可以直接映射到本地8787端口
