### ISSUE TITLE
客户端（dtunnel）连接后立刻断开！

### ISSUE THREAD

**Issue by miyouzi** [vzex/dog-tunnel#80]
我想做的是反向端口映射，将本地的80端口映射到服务器的87端口。
我是自搭建的服务端（dtunnel_s），CentOS环境。
本地客户端是Win10环境。（这里举例客户端ip是111.111.111.111）
服务端以 `./dtunnel_s` 启动。（这里举例服务端的的ip是123.123.123.123）
本地客户端以以下指令启动：
`dtunnel -buster 123.123.123.123:8018 -reg miyouzi -local 80 -clientkey 123456 -remote=123.123.123.123:8000 -ssl=false -v`
结果是一连上马上断开。
本地客户端显示：
connect to server succeed
2017/01/15 19:10:47 init client {"AccessKey":"","ClientKey":"123456","Name":"miyouzi","ClientType":"reg","Version":0.7,"Delay":2,"Mode":0,"PipeNum":1,"AesKey":""}
2017-01-15 19:10:47 client version:0.70 not eq with server:0.80
read tcp 111.111.111.111:2709->123.123.123.123:8000: use of closed network connection
2017/01/15 19:10:47 service shutdown

服务端显示：
2017/01/15 06:10:41 client linked success 111.111.111.111:2709
2017/01/15 06:10:41 version not eq 111.111.111.111:2709 0.80 0.70
2017/01/15 06:10:41 client disconnected 111.111.111.111:2709

请问怎么解决？

**Comment by vzex** [comment]
两端版本号不一致， 服务端版本0.8，客户端是0.7

**Comment by miyouzi** [comment]
请问一下有Win32已编译好的0.8版本吗？

**Comment by vzex** [comment]
目前还没有release，所以可以自行下载编译

**Comment by miyouzi** [comment]
嗯。好的。谢谢
