### ISSUE TITLE
dog-tunnel.tk域名被关了，是因为访问量过大么？

### ISSUE THREAD

**Issue by cy18** [vzex/dog-tunnel#81]
我发现dog-tunnel.tk域名访问不了了，听说tk的域名访问量到一定程度就会被收回去，不知道是不是这原因？现在找不到客户的下载地址了- -略尴尬- -

**Comment by vzex** [comment]
你好，域名到了一年续期了，重置了我的第三方dns服务器记录导致无法解析地址，我刚更新了一下，应该24小时内恢复

**Comment by cy18** [comment]
我这边可以了- -我以为tk又封域名了- -|
