### ISSUE TITLE
请问下载编译的mips和mipsle版本是32位的吗

### ISSUE THREAD

**Issue by kkstun** [vzex/dog-tunnel#82]
请问下载编译的mips和mipsle版本是32位的吗,我在我的openwrt上没有运行成功system type		: MediaTek MT7620N ver:2 eco:3
mipsle版本:Illegal instruction
mips版本:line 1: syntax error: unexpected "("

**Comment by vzex** [comment]
你好， 是32位的，不过我没有测试过

**Comment by kkstun** [comment]
我看了下是32位了. 使用go哪个版本编译的 1.4还是1.5呢

**Comment by vzex** [comment]
go 1.8 加入了32位mips的原生支持，但是有限制
Go now supports 32-bit MIPS on Linux for both big-endian (linux/mips) and little-endian machines (linux/mipsle) that implement the MIPS32r1 instruction set with FPU or kernel FPU emulation. Note that many common MIPS-based routers lack an FPU and have firmware that doesn't enable kernel FPU emulation; Go won't run on such machines.
低版本的可能需要openwrt-go进行编译，而且需要专门的kernel固件支持，所以如果即使32位的mips平台可能也会无法运行

**Comment by vzex** [comment]
https://github.com/golang/go/issues/18880

**Comment by seatrix** [comment]
我编译了一个openwrt mt7620A的可以用

**Comment by hbxntsxw** [comment]
我下载@vzex编译的版本能够正常使用。我路由器固件是老毛子的Padavan。

**Comment by kkstun** [comment]
我重新编译可以在openwrt下使用.
