### ISSUE TITLE
参数在命令行中的位置会影响效果（-ssl=false）

### ISSUE THREAD

**Issue by hxhxd** [vzex/dog-tunnel#91]
自设服务器前面尝试n次都失败  
后面将-ssl=false加到前面，放在-remote的后面，便连接成功了。

**Comment by wxlg1117** [comment]
我都是放在最后，一点问题都没有啊

**Comment by hxhxd** [comment]
看来是我参数的问题。 我在最后加了 reg/link 且无 -
谢谢 ：）
