### ISSUE TITLE
dtunnel_lite 加上compress参数之后 mysql-slave 连接异常

### ISSUE THREAD

**Issue by bhzhu203** [vzex/dog-tunnel#96]
/usr/bin/dtunnel_lite -compress  -service x.x.x.x:5234 -v -action 127.0.0.1:3306 -encrypt -local :33070 -auth xxxxx.com -pipe 3

mysql slave （mariadb“10.1.14-MariaDB ”）端使用上面的命令映射3306tcp端口 ，会出现slave连接异常的情况，要不就一直connecting，要不就连接timeout。刚开始连接是正常的，telnet也是正常的。然后使用了1分钟左右slave就一直connecting，telnet虽然是通的，但是已经不显示mysql/mariadb的欢迎信息

然后去掉 -compress参数就连接正常了

正常telnet ：
telnet 127.0.0.1 33070
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Y
5.5.5-10.1.19-MariaDBU$rISHM)$x!?�SvvmA;C~tHM*mysql_native_password

不正常telnet：
Trying 127.0.0.1...
Connected to 127.0.0.1...
Escape character is '^]'.

**Comment by bhzhu203** [comment]
好像 compress参数不是很稳定呀，刚才使用这个参数测试的时候 -action socks5 -smartN 3 -dnscache 10 -tcp=false -compress 

网页页面刷不出来

**Comment by vzex** [comment]
应该修复了
